/* ゲームデータ。数値調整はこのファイルだけで完結するようにしている。
   条件(cond)の書式: {flag:'x'} {notFlag:'x'} {tech:'x'} {era:n} {res:{money:10}} {bld:{kama:2}} {time:秒} {pop:n} {all:[...]} {any:[...]} */
var TM = window.TM = window.TM || {};

TM.DATA = {
  version: 1,

  /* ---------------- 資源 ---------------- */
  resources: [
    { id: 'money', name: '円', unit: '円', cap: null, grp: 'money' },
    { id: 'scrap', name: '鉄くず', unit: '個', cap: 15, grp: 'raw' },
    { id: 'hcl', name: '塩酸', alias: { name: '? 液', untilFlag: 'acid_known' }, unit: 'kg', cap: 30, grp: 'raw' },
    { id: 'hclw', name: '受入塩酸（検査待ち）', unit: 'kg', cap: 0, grp: 'raw' },
    { id: 'fecl2', name: '塩化第一鉄液', alias: { name: '緑の液', untilFlag: 'fecl2_known' }, unit: 'kg', cap: 30, grp: 'liq' },
    { id: 'fecl3w', name: '第二鉄液（検査待ち）', unit: 'kg', cap: 0, grp: 'liq' },
    { id: 'fecl3', name: '塩化第二鉄液', unit: 'kg', cap: 0, grp: 'liq' },
    { id: 'fecl3h', name: '第二鉄液（高濃度）', unit: 'kg', cap: 0, grp: 'liq' },
    { id: 'can', name: '空きポリ缶', unit: '個', cap: 10, grp: 'can' },
    { id: 'dcan', name: '汚れた缶', unit: '個', cap: 20, grp: 'can' },
    { id: 'p_fecl2', name: '缶入り 第一鉄液', unit: '缶', cap: 10, grp: 'prod' },
    { id: 'p_hcl', name: '缶入り 塩酸', unit: '缶', cap: 10, grp: 'prod' },
    { id: 'p_fecl3', name: '缶入り 第二鉄液', unit: '缶', cap: 10, grp: 'prod' },
    { id: 'p_fecl3h', name: '缶入り 高濃度品', unit: '缶', cap: 10, grp: 'prod' },
    { id: 'p_naclo', name: '缶入り 次亜塩素酸ソーダ', unit: '缶', cap: 0, grp: 'prod' },
    { id: 'p_uw', name: 'BIB入り 尿素水', unit: '箱', cap: 0, grp: 'prod' },
    { id: 'waste', name: '排水', unit: 'L', cap: 120, grp: 'water' },
    { id: 'spent', name: '使用済み液', unit: 'kg', cap: 0, grp: 'raw' },
    { id: 'cu', name: '回収銅', unit: 'kg', cap: 0, grp: 'liq' },
    { id: 'cup', name: '精製銅', unit: 'kg', cap: 0, grp: 'liq' },
    { id: 'pw', name: '純水', unit: 'L', cap: 0, grp: 'water' },
    { id: 'upw', name: '超純水', unit: 'L', cap: 0, grp: 'water' },
    { id: 'nacw', name: '次亜（検査待ち）', unit: 'kg', cap: 0, grp: 'liq' },
    { id: 'naclo', name: '次亜塩素酸ソーダ', unit: 'kg', cap: 0, grp: 'liq' },
    { id: 'pac', name: 'PAC', unit: 'kg', cap: 0, grp: 'liq' },
    { id: 'psi', name: 'ポリシリカ鉄', unit: 'kg', cap: 0, grp: 'liq' },
    { id: 'urea', name: '尿素', unit: 'kg', cap: 0, grp: 'raw' },
    { id: 'uww', name: '尿素水（検査待ち）', unit: 'kg', cap: 0, grp: 'liq' },
    { id: 'uw', name: '尿素水（AUS32）', unit: 'kg', cap: 0, grp: 'liq' },
    { id: 'hp', name: '高純度薬品', unit: 'kg', cap: 0, grp: 'liq' },
    { id: 'h2', name: '水素', unit: 'kg', cap: 0, grp: 'liq' },
    { id: 'fuel', name: 'ロケット燃料', unit: 't', cap: 0, grp: 'space' },
    { id: 'orbit', name: '軌道資材', unit: 't', cap: null, grp: 'space' },
    { id: 'moonfe', name: '月の砂鉄', unit: 't', cap: null, grp: 'space' },
    { id: 'vhcl', name: '金星の塩化水素', unit: 't', cap: null, grp: 'space' },
    { id: 'aster', name: '小惑星の鉄', unit: 't', cap: null, grp: 'space' },
    { id: 'sfecl3', name: '宇宙製 塩化第二鉄', unit: 't', cap: null, grp: 'space' },
    { id: 'star', name: '恒星エネルギー', unit: '', cap: null, grp: 'space' },
    { id: 'ism', name: '星間物質', unit: '', cap: null, grp: 'space' },
    { id: 'gfe', name: '星の鉄', unit: '', cap: null, grp: 'space' },
    { id: 'research', name: '技術', unit: 'pt', cap: 100, grp: 'lab' },
    { id: 'credit', name: '信用', unit: '', cap: null, grp: 'money' }
  ],

  /* 資源欄の見出し（grp の順に並べる） */
  resGroups: [
    { id: 'money', name: '' },
    { id: 'raw', name: '原料（仕入れる）' },
    { id: 'liq', name: 'タンクの液（つくったもの）' },
    { id: 'can', name: '缶' },
    { id: 'prod', name: '売り物（缶・箱）' },
    { id: 'water', name: '水・排水' },
    { id: 'lab', name: '研究' },
    { id: 'space', name: '宇宙' }
  ],

  /* ロット：検査待ち → 合格 */
  lots: [
    { wait: 'fecl3w', ok: 'fecl3' },
    { wait: 'hclw', ok: 'hcl' },
    { wait: 'nacw', ok: 'naclo' },
    { wait: 'uww', ok: 'uw' }
  ],

  /* ---------------- 人手の配属 ---------------- */
  jobs: [
    { id: 'gather', name: '回収', desc: '鉄くずを拾い集める。', unlock: { flag: 'hired' },
      in: {}, out: { scrap: 0.12 } },
    { id: 'dissolve', name: '溶解', desc: '鉄くずを塩酸に沈める。釜1つにつき2人まで。', unlock: { bld: { kama: 1 } },
      in: { scrap: 0.1, hcl: 0.2 }, out: { fecl2: 0.3 }, slotsFrom: 'dissolve', fumes: true, rinse: true },
    { id: 'fill', name: '充填', desc: '液を20kgずつ缶に詰める。充填台・小分けラインの操作もここから。', unlock: { flag: 'cans_known' },
      special: 'fill', rate: 0.035 },
    { id: 'deliver', name: '配達', desc: '缶を客先へ届ける。トラック・ローリーの運転手もここから。', unlock: { flag: 'cans_known' },
      special: 'deliver', rate: 0.012 },
    { id: 'wash', name: '洗缶', desc: '汚れた缶を洗って再び使えるようにする。排水が出る。', unlock: { flag: 'dcan_known' },
      in: { dcan: 0.03 }, out: { can: 0.03, waste: 0.3 } },
    { id: 'research', name: '研究', desc: '帳面をつけ、工夫を考える。', unlock: { flag: 'research_known' },
      in: {}, out: { research: 0.08 } },
    { id: 'operate', name: '運転', desc: '反応槽・塩素化設備などを動かす。1基につき1人。', unlock: { tech: 'reactor' },
      special: 'operate' },
    { id: 'check', name: '検査', desc: '検査待ちの液を確かめ、合格品にする。', unlock: { tech: 'chlorination' },
      special: 'check' },
    { id: 'handle', name: '荷役', desc: '荷を動かす。フォークリフトの運転もここから。', unlock: { tech: 'logistics' },
      special: 'handle', rate: 0.6 },
    { id: 'sales', name: '営業', desc: '受託案件を進める。1人で1件。', unlock: { tech: 'oem' },
      special: 'sales' }
  ],

  /* ---------------- 資格 ---------------- */
  licenses: [
    { id: 'geki', name: '劇物の取扱責任者', desc: '劇物（塩酸など）を小分けして売るのに必要。', cost: { money: 2500 }, time: 900, unlock: { tech: 'poison' } },
    { id: 'fork', name: 'フォークリフト運転技能講習', desc: 'フォークリフトを動かすのに必要。', cost: { money: 6000 }, time: 600, unlock: { tech: 'logistics' } },
    { id: 'jmid', name: '準中型免許', desc: '2tトラックの運転に必要。', cost: { money: 12000 }, time: 1200, unlock: { tech: 'trucks' } },
    { id: 'mid', name: '中型免許', desc: '4tトラックの運転に必要（2tも運転できる）。', cost: { money: 30000 }, time: 1800, unlock: { tech: 'trucks2' } },
    { id: 'big', name: '大型免許', desc: 'タンクローリーの運転に必要（トラックもすべて運転できる）。', cost: { money: 150000 }, time: 2400, unlock: { tech: 'lorry' } },
    { id: 'crane', name: '玉掛け・クレーン運転', desc: '天井クレーンを動かすのに必要。', cost: { money: 40000 }, time: 1200, unlock: { tech: 'crane' } }
  ],

  /* ---------------- 設備 ---------------- */
  buildings: [
    /* ---- 時代0〜1：工房 ---- */
    { id: 'kama', name: '釜', group: '製造', desc: '鉄くずを溶かす釜。溶解の人手を2人まで置ける。', unlock: { flag: 'kama_reveal' },
      cost: { money: 60 }, ratio: 1.17, space: 2, effects: { slots: { dissolve: 2 }, cap: { fecl2: 20 } } },
    { id: 'shed', name: '物置', group: '保管', desc: '鉄くずと塩酸を置ける場所。', unlock: { all: [{ era: 1 }, { any: [{ flag: 'raw_full' }, { bld: { kama: 2 } }] }] },
      cost: { money: 50 }, ratio: 1.2, space: 3, effects: { cap: { scrap: 20, hcl: 30 } } },
    { id: 'house', name: '寮', group: '人', desc: '住み込みの人手が増やせる。', unlock: { all: [{ era: 1 }, { pop: 3 }] },
      cost: { money: 80 }, ratio: 1.24, space: 4, effects: { popCap: 2 } },
    { id: 'desk', name: '机と帳面', group: '研究', desc: '考えたことを書き留めておける。', unlock: { flag: 'research_known' },
      cost: { money: 100 }, ratio: 1.22, space: 1, effects: { cap: { research: 100 } } },
    { id: 'canyard', name: '缶置き場', group: '容器', desc: '空き缶・汚れた缶・製品の缶を置ける。', unlock: { flag: 'cans_known' },
      cost: { money: 90 }, ratio: 1.2, space: 3, effects: { cap: { can: 20, dcan: 20, p_fecl2: 10, p_hcl: 10, p_fecl3: 10, p_fecl3h: 10, p_naclo: 10, p_uw: 10 } } },
    { id: 'canbuy', name: '缶の仕入れ契約', group: '容器', desc: '新品のポリ缶を定期的に買う（1缶15円）。', unlock: { flag: 'cans_known', res: { money: 150 } },
      cost: { money: 220 }, ratio: 1.3, space: 0, proc: { in: { money: 0.9 }, out: { can: 0.06 }, toggle: true, handling: 0.06 } },
    { id: 'scrapbuy', name: 'スクラップ業者', group: '製造', desc: '鉄くずを買い付ける（1個2円）。', unlock: { tech: 'suppliers' },
      cost: { money: 350 }, ratio: 1.3, space: 0, proc: { in: { money: 0.5 }, out: { scrap: 0.25 }, toggle: true, handling: 0.025 } },
    { id: 'acidbuy', name: '塩酸の配達', group: '製造', desc: '店の主人に、塩酸を缶で定期的に届けてもらう。空いた缶は残る。', unlock: { era: 1, flag: 'acid_known', stat: { acidBuys: 8 } },
      cost: { money: 120 }, ratio: 1.35, space: 0, proc: { in: { money: 1.0 }, out: { hcl: 0.6, dcan: 0.03 }, toggle: true, handling: 0.03, spill: ['dcan'] } },
    { id: 'vent', name: '換気扇', group: '用役', desc: '酸の霧と泡（水素）を外へ逃がす。', unlock: { flag: 'smoke' },
      cost: { money: 200 }, ratio: 1.25, space: 0, effects: { vent: 1.2 }, proc: { power: 1 } },
    { id: 'powerc', name: '電力契約の増強', group: '用役', desc: '使える電気が増える。', unlock: { flag: 'power_known' },
      cost: { money: 400 }, ratio: 1.4, space: 0, effects: { power: 5 } },
    { id: 'land', name: '隣の空き地', group: '敷地', desc: '敷地が広がる。', unlock: { flag: 'space_tight' },
      cost: { money: 600 }, ratio: 1.4, space: 0, effects: { land: 30 } },
    { id: 'scrubber', name: 'スクラバー', group: '用役', desc: '排気の酸を水で捕まえる。換気が大きく改善し、回収した希塩酸が溶解に戻る。', unlock: { tech: 'scrubbing' },
      cost: { money: 3500 }, ratio: 1.3, space: 3, effects: { vent: 6, hclRecover: 0.04, circ: { hcl: 1 } }, proc: { power: 3 } },
    { id: 'reactor', name: 'FRP反応槽', group: '製造', desc: '大きな槽でまとめて溶かす。運転1人と電気が要る。', unlock: { tech: 'reactor' },
      cost: { money: 2200 }, ratio: 1.2, space: 6, effects: { cap: { fecl2: 120 } },
      proc: { in: { scrap: 0.5, hcl: 1.0 }, out: { fecl2: 1.5 }, power: 2, operator: 'operate', toggle: true, rinse: true, fumes: true } },
    { id: 'chlor', name: '塩素化設備', group: '製造', desc: '塩素で第一鉄液を第二鉄液に変える。液は赤褐色になる。塩素代がかかる。', unlock: { tech: 'chlorination' },
      cost: { money: 3800 }, ratio: 1.25, space: 5, effects: { cap: { fecl3w: 120, fecl3: 160 } },
      proc: { in: { fecl2: 1.0, money: 0.35 }, out: { fecl3w: 1.0 }, power: 2, operator: 'operate', toggle: true, rinse: true } },
    { id: 'study', name: '研究小屋', group: '研究', desc: '考えるための部屋。研究を進め、技術をためておける。紙代がかかる。', unlock: { tech: 'bookkeeping' },
      cost: { money: 1500 }, ratio: 1.3, space: 3, effects: { cap: { research: 150 } }, proc: { in: { money: 0.2 }, out: { research: 0.3 }, toggle: true } },
    { id: 'kei', name: '軽トラック', group: '物流', desc: '町まで配達できる。運転手（配達の人手）が1人要る。', unlock: { tech: 'delivery' },
      cost: { money: 1200 }, ratio: 1.3, space: 3, effects: { transport: { rate: 0.12, zone: 1 } } },
    { id: 'mega1', name: '工場の建屋', group: '大型', desc: '屋根と壁のある工場。5段階で完成。完成すると敷地が大きく広がる。', unlock: { tech: 'factory' },
      cost: { money: 7000 }, ratio: 1.4, space: 0, stages: 5, onComplete: { era: 2, land: 120, popCap: 6 } },

    /* ---- 時代2：工場 ---- */
    { id: 'lab', name: '分析室', group: '品質', desc: 'ロットを素早く確かめる。品質が上がり単価が上がる。', unlock: { tech: 'analysis' },
      cost: { money: 14000 }, ratio: 1.3, space: 4, effects: { checkCap: 4, quality: 0.1 }, proc: { power: 2 } },
    { id: 'i_refract', name: 'デジタル屈折率計', group: '品質', max: 1, desc: '液の屈折率から濃度をすぐ測る。検査が速くなる。尿素水の濃度管理に欠かせない。', unlock: { bld: { lab: 1 } },
      cost: { money: 20000 }, ratio: 1, space: 0, effects: { checkCap: 6, quality: 0.05 } },
    { id: 'pallet', name: 'パレット置き場', group: '保管', desc: '製品の缶をパレットに積んで置く。', unlock: { tech: 'logistics' },
      cost: { money: 2500 }, ratio: 1.2, space: 4, effects: { cap: { p_fecl2: 40, p_hcl: 40, p_fecl3: 40, p_fecl3h: 40, p_naclo: 40, p_uw: 40, can: 40, dcan: 40 } } },
    { id: 'fork', name: 'フォークリフト', group: '保管', desc: '荷役が大きく速くなる。資格を持つ荷役の人手が運転する。', unlock: { tech: 'logistics' },
      cost: { money: 11000 }, ratio: 1.25, space: 2, effects: { forklift: 5 }, proc: { power: 1 } },
    { id: 'rack', name: 'ラック', group: '保管', desc: '高く積める棚。フォークリフトがないと使えない。', unlock: { tech: 'racking' },
      cost: { money: 9000 }, ratio: 1.25, space: 3, effects: { cap: { p_fecl2: 150, p_hcl: 150, p_fecl3: 150, p_fecl3h: 150, p_naclo: 150, p_uw: 150, can: 120, dcan: 120 }, needs: 'fork' } },
    { id: 'truck2', name: '2tトラック', group: '物流', desc: '県内まで届く。準中型免許の運転手が要る。', unlock: { tech: 'trucks' },
      cost: { money: 9000 }, ratio: 1.3, space: 5, effects: { transport: { rate: 0.5, zone: 2, license: 'jmid' } } },
    { id: 'truck4', name: '4tトラック', group: '物流', desc: 'たくさん積める。中型免許の運転手が要る。', unlock: { tech: 'trucks2' },
      cost: { money: 26000 }, ratio: 1.3, space: 7, effects: { transport: { rate: 1.3, zone: 2, license: 'mid' } } },
    { id: 'canwasher', name: '洗缶機', group: '容器', desc: '缶をまとめて洗う。排水が多く出る。', unlock: { tech: 'washing' },
      cost: { money: 16000 }, ratio: 1.3, space: 6, effects: { circ: { can: 1 } }, proc: { in: { dcan: 0.35 }, out: { can: 0.35, waste: 3.5 }, power: 3, toggle: true } },
    { id: 'neutral', name: '中和槽', group: '用役', desc: '排水を中和して流せるようにする。', unlock: { tech: 'wastewater' },
      cost: { money: 7000 }, ratio: 1.3, space: 3, effects: { cap: { waste: 200 } }, proc: { in: { waste: 1.5, money: 0.15 }, out: {}, toggle: true } },
    { id: 'coag', name: '凝集沈殿槽', group: '用役', desc: '自社の塩化第二鉄液で排水の濁りを沈める。', unlock: { tech: 'wastewater' },
      cost: { money: 18000 }, ratio: 1.3, space: 5, effects: { cap: { waste: 500 } }, proc: { in: { waste: 7, fecl3: 0.08, money: 0.25 }, out: {}, power: 1, toggle: true } },
    { id: 'filler', name: '半自動充填台', group: '充填', desc: '決まった量を自動で注ぐ。充填の人手1人で動かす。', unlock: { tech: 'filling' },
      cost: { money: 8000 }, ratio: 1.25, space: 3, effects: { filler: 0.14 }, proc: { power: 1 } },
    { id: 'line', name: '小分けライン', group: '充填', desc: 'ベルトコンベアでつないだ充填ライン。充填の人手2人で動かす。能力は一番遅い工程で決まる（ラインタブ）。', unlock: { tech: 'conveyor' },
      cost: { money: 32000 }, ratio: 1.4, space: 10, effects: { line: 1 }, proc: { power: 4 } },
    { id: 'substation', name: '受変電設備', group: '用役', desc: '高圧で電気を受ける。使える電気が大きく増える。', unlock: { tech: 'substation' },
      cost: { money: 38000 }, ratio: 1.4, space: 4, effects: { power: 40 } },
    { id: 'boiler', name: 'ボイラー', group: '用役', desc: '蒸気をつくる。濃縮・溶解の熱源。燃料代がかかる。', unlock: { tech: 'concentration' },
      cost: { money: 15000 }, ratio: 1.3, space: 3, effects: { steam: 1 }, proc: { in: { money: 0.4 }, out: {}, toggle: true } },
    { id: 'conc', name: '濃縮設備', group: '製造', desc: '第二鉄液を煮詰めて高濃度品にする。ボイラーの蒸気が要る。', unlock: { tech: 'concentration' },
      cost: { money: 24000 }, ratio: 1.3, space: 5, effects: { cap: { fecl3h: 150 } },
      proc: { in: { fecl3: 1.25 }, out: { fecl3h: 1.0 }, power: 2, toggle: true, needs: 'boiler' } },
    { id: 'drum', name: 'ドラム・コンテナ充填', group: '充填', desc: '大口の客向けに、ドラムやコンテナで出す。注文が増える。', unlock: { tech: 'bigpack' },
      cost: { money: 45000 }, ratio: 1.35, space: 4, effects: { bigpack: 1 } },
    { id: 'crane', name: '天井クレーン', group: '保管', desc: 'ドラム・コンテナ・フレコンをまとめて吊る。荷役が大きく増える。玉掛け・クレーンの資格者が要る。', unlock: { tech: 'crane' },
      cost: { money: 60000 }, ratio: 1.3, space: 0, effects: { crane: 20 }, proc: { power: 3 } },
    { id: 'rlab', name: '研究室', group: '研究', desc: '試験管とビーカー。研究が進む。', unlock: { era: 2 },
      cost: { money: 20000 }, ratio: 1.3, space: 3, effects: { cap: { research: 2000 } }, proc: { in: { money: 1.5 }, out: { research: 1.2 }, power: 1, toggle: true } },
    { id: 'mega2', name: '連続プラント', group: '大型', desc: '溶解から充填までを一つにつなぐ。8段階で完成。', unlock: { tech: 'plant' },
      cost: { money: 90000 }, ratio: 1.42, space: 0, stages: 8, onComplete: { era: 3, land: 300, popCap: 20 } },

    /* ---- 時代3：基地 ---- */
    { id: 'shiptank', name: '出荷タンク', group: '物流', desc: 'ローリーへ積む液をためる大きなタンク。', unlock: { tech: 'lorry' },
      cost: { money: 180000 }, ratio: 1.3, space: 6, effects: { cap: { fecl3: 3000, fecl3h: 2000, naclo: 2000, uw: 3000, pac: 2000, psi: 2000 } } },
    { id: 'dike', name: '防液堤', group: '物流', desc: '大きなタンクの周りを囲う堤。ローリー出荷の前提。', unlock: { tech: 'lorry' },
      cost: { money: 120000 }, ratio: 1.6, space: 2, max: 3 },
    { id: 'loader', name: 'ローリー充填所', group: '物流', desc: 'ローディングアームでローリーに液を積む。', unlock: { tech: 'lorry' },
      cost: { money: 250000 }, ratio: 1.6, space: 4, max: 3 },
    { id: 'tscale', name: 'トラックスケール', group: '物流', desc: '車ごと量る大きなはかり。', unlock: { tech: 'lorry' },
      cost: { money: 200000 }, ratio: 1.6, space: 4, max: 2 },
    { id: 'lorry', name: 'タンクローリー（10t）', group: '物流', desc: '液をそのまま大量に運ぶ（地方まで）。大型免許の運転手と、出荷タンク・防液堤・充填所・トラックスケールが要る。', unlock: { tech: 'lorry' },
      cost: { money: 400000 }, ratio: 1.25, space: 6, effects: { transport: { kind: 'bulk', rate: 40, zone: 3, license: 'big', requires: ['shiptank', 'dike', 'loader', 'tscale'] } } },
    { id: 'lorry20', name: 'タンクローリー（20t）', group: '物流', desc: '全国へ。中継デポが要る。', unlock: { tech: 'depot' },
      cost: { money: 3000000 }, ratio: 1.25, space: 8, effects: { transport: { kind: 'bulk', rate: 110, zone: 4, license: 'big', requires: ['shiptank', 'dike', 'loader', 'tscale', 'depot'] } } },
    { id: 'depot', name: '中継デポ', group: '物流', desc: '遠くの町に置く小さな基地。全国へ届けられる。', unlock: { tech: 'depot' },
      cost: { money: 5000000 }, ratio: 1.5, space: 0, effects: { cap: { fecl3: 5000, uw: 8000, naclo: 3000 } } },
    { id: 'acidtank', name: '塩酸の受入タンク', group: '製造', desc: '塩酸をローリーで大口に受け入れる。安いが、受入検査が要る。', unlock: { tech: 'lorry' },
      cost: { money: 150000 }, ratio: 1.3, space: 4, effects: { cap: { hclw: 2000, hcl: 2000 } },
      proc: { in: { money: 25 }, out: { hclw: 40 }, toggle: true } },
    { id: 'scrapyard', name: 'スクラップヤード', group: '製造', desc: '鋼材の端材を定期契約で受け入れる。荷役を使う。', unlock: { tech: 'lorry' },
      cost: { money: 90000 }, ratio: 1.3, space: 6, effects: { cap: { scrap: 2000 } },
      proc: { in: { money: 3 }, out: { scrap: 3 }, toggle: true, handling: 0.6 } },
    { id: 'bigreactor', name: '大型反応槽', group: '製造', desc: '一度に大量に溶かす。ロットが大きくなり、検査の手間が減る。', unlock: { tech: 'lorry' },
      cost: { money: 300000 }, ratio: 1.22, space: 8, effects: { cap: { fecl2: 2000 } },
      proc: { in: { scrap: 4, hcl: 8 }, out: { fecl2: 12 }, power: 8, operator: 'operate', toggle: true, rinse: true, fumes: true } },
    { id: 'bigchlor', name: '大型塩素化設備', group: '製造', desc: '大量の第一鉄液を第二鉄液に。', unlock: { tech: 'lorry' },
      cost: { money: 400000 }, ratio: 1.25, space: 6, effects: { cap: { fecl3w: 2000, fecl3: 2000 } },
      proc: { in: { fecl2: 10, money: 3 }, out: { fecl3w: 10 }, power: 6, operator: 'operate', toggle: true, rinse: true } },
    { id: 'lab2', name: '分析室の増設', group: '品質', desc: '分析員と機器を増やす。', unlock: { tech: 'lorry' },
      cost: { money: 250000 }, ratio: 1.35, space: 3, effects: { checkCap: 80, quality: 0.02 }, proc: { power: 4 } },
    { id: 'i_cond', name: '電気伝導度計', group: '品質', max: 1, desc: '水の純度を測る。純水装置の運転に要る。', unlock: { tech: 'purewater' },
      cost: { money: 80000 }, ratio: 1, space: 0 },
    { id: 'i_uv', name: '紫外可視分光光度計', group: '品質', max: 1, desc: '微量の副生成分を測る。品質が上がる。', unlock: { tech: 'instruments' },
      cost: { money: 400000 }, ratio: 1, space: 0, effects: { quality: 0.1 } },
    { id: 'i_aa', name: '原子吸光光度計', group: '品質', max: 1, desc: '微量の重金属を測る。浄水場向けの品質。使用済み液の銅も測れる。', unlock: { tech: 'instruments' },
      cost: { money: 600000 }, ratio: 1, space: 0, effects: { quality: 0.1, checkCap: 10 } },
    { id: 'i_ic', name: 'イオンクロマトグラフィー', group: '品質', max: 1, desc: '次亜塩素酸ソーダの塩素酸・臭素酸を測る。次亜を売るのに要る。', unlock: { tech: 'hypo' },
      cost: { money: 700000 }, ratio: 1, space: 0, effects: { checkCap: 10 } },
    { id: 'i_visc', name: '粘度計', group: '品質', max: 1, desc: '凝集剤の粘りを測る。PAC・ポリシリカ鉄を売るのに要る。', unlock: { tech: 'coagulants' },
      cost: { money: 300000 }, ratio: 1, space: 0 },
    { id: 'i_icp', name: 'ICP発光分光分析装置', group: '品質', max: 1, desc: '多元素を一度に測る。尿素水の多項目分析に要る。超純水がないと動かない。', unlock: { tech: 'urea' },
      cost: { money: 2500000 }, ratio: 1, space: 0, effects: { checkCap: 120, quality: 0.1, needsRes: 'upw' }, proc: { in: { upw: 0.5 }, out: {}, power: 3 } },
    { id: 'i_ftir', name: 'フーリエ変換分光光度計', group: '品質', max: 1, desc: '分子の形から、中身の分からない物質を見分ける。受託の幅が広がる。', unlock: { tech: 'oem' },
      cost: { money: 1800000 }, ratio: 1, space: 0, effects: { quality: 0.05 } },
    { id: 'decopper', name: '脱銅処理設備', group: '製造', desc: '使用済みエッチング液から銅を取り出し、第二鉄液に再生する。', unlock: { tech: 'decopper' },
      cost: { money: 350000 }, ratio: 1.3, space: 5, effects: { cap: { spent: 3000, cu: 500 }, circ: { cu: 1 } },
      proc: { in: { spent: 3 }, out: { fecl3w: 2.4, cu: 0.06 }, power: 3, toggle: true, rinse: true } },
    { id: 'cooler', name: '冷却設備', group: '用役', desc: '次亜塩素酸ソーダを冷やして貯める（分解・副生成分を抑える）。', unlock: { tech: 'hypo' },
      cost: { money: 250000 }, ratio: 1.3, space: 3, effects: { cap: { naclo: 800, nacw: 400, p_naclo: 30 } }, proc: { power: 3 } },
    { id: 'hypoline', name: '次亜の希釈槽', group: '製造', desc: '次亜塩素酸ソーダを純水で決まった濃度に合わせる。', unlock: { tech: 'hypo' },
      cost: { money: 200000 }, ratio: 1.3, space: 3, proc: { in: { money: 4, pw: 3 }, out: { nacw: 6 }, toggle: true, power: 1, needs: 'cooler' } },
    { id: 'pacline', name: 'PAC調整槽', group: '製造', desc: '凝集剤PACを仕入れて調整する。', unlock: { tech: 'coagulants' },
      cost: { money: 220000 }, ratio: 1.3, space: 3, effects: { cap: { pac: 1500 } }, proc: { in: { money: 5, pw: 2 }, out: { pac: 8 }, toggle: true, power: 1 } },
    { id: 'psiline', name: 'ポリシリカ鉄設備', group: '製造', desc: 'シリカと鉄の凝集剤。アルミを含まない。汚泥は田畑に還せる。', unlock: { tech: 'coagulants' },
      cost: { money: 500000 }, ratio: 1.3, space: 5, effects: { cap: { psi: 1500 } }, proc: { in: { fecl3: 2, money: 3 }, out: { psi: 5 }, toggle: true, power: 3 } },
    { id: 'pwplant', name: '純水装置', group: '用役', desc: '水道水 → 前処理 → 逆浸透膜 → イオン交換 → 紫外線殺菌。膜と樹脂は消耗品。', unlock: { tech: 'purewater' },
      cost: { money: 300000 }, ratio: 1.3, space: 4, effects: { cap: { pw: 3000 } }, proc: { in: { money: 1.5 }, out: { pw: 12 }, power: 4, toggle: true, needs: 'i_cond' } },
    { id: 'upwplant', name: '超純水装置', group: '用役', desc: '純水をさらに磨く（18MΩ·cm）。ICPやイオンクロマトの超微量分析に。', unlock: { tech: 'urea' },
      cost: { money: 900000 }, ratio: 1.4, space: 2, effects: { cap: { upw: 300 } }, proc: { in: { pw: 2, money: 1 }, out: { upw: 1 }, power: 2, toggle: true } },
    { id: 'ureabuy', name: '尿素フレコンの受入', group: '製造', desc: '1tのフレコンで尿素を受け入れる。重いので荷役（クレーン）を食う。', unlock: { tech: 'urea' },
      cost: { money: 400000 }, ratio: 1.3, space: 4, effects: { cap: { urea: 3000 } }, proc: { in: { money: 8 }, out: { urea: 4 }, toggle: true, handling: 2 } },
    { id: 'ureadis', name: '尿素溶解槽', group: '製造', desc: '尿素を純水に溶かす。溶けると冷える（吸熱）ので、ボイラーの蒸気で温める。', unlock: { tech: 'urea' },
      cost: { money: 600000 }, ratio: 1.3, space: 5, effects: { cap: { uww: 2000, uw: 2000 } },
      proc: { in: { urea: 3.25, pw: 6.75 }, out: { uww: 10 }, power: 3, toggle: true, needs: 'boiler' } },
    { id: 'bibline', name: 'BIB充填', group: '充填', desc: '尿素水をバッグインボックスに詰める。洗缶はいらない。', unlock: { tech: 'urea' },
      cost: { money: 350000 }, ratio: 1.3, space: 3, effects: { filler: 0.8, cap: { p_uw: 200 } }, proc: { power: 1 } },
    { id: 'canline', name: '自動洗缶ライン', group: '容器', desc: '反転・洗浄・すすぎ・乾燥・検査を一貫で。仕上げのすすぎに純水を使う。', unlock: { tech: 'autowash' },
      cost: { money: 1200000 }, ratio: 1.35, space: 8, effects: { circ: { can: 3 } }, proc: { in: { dcan: 3, pw: 1 }, out: { can: 3, waste: 20 }, power: 6, toggle: true } },
    { id: 'office', name: '営業所', group: '人', desc: '営業の拠点。人手と受託の枠が増える。', unlock: { tech: 'oem' },
      cost: { money: 800000 }, ratio: 1.45, space: 0, effects: { popCap: 10 } },
    { id: 'rnd', name: '中央研究所', group: '研究', desc: '研究員と設備をそろえた研究所。', unlock: { era: 3 },
      cost: { money: 1500000 }, ratio: 1.32, space: 6, proc: { in: { money: 30 }, out: { research: 25 }, power: 10, toggle: true } },
    { id: 'mega3', name: '貯蔵出荷基地', group: '大型', desc: '大型タンク群とローリー網。10段階で完成。', unlock: { tech: 'terminal' },
      cost: { money: 2200000 }, ratio: 1.38, space: 0, stages: 10, onComplete: { era: 4, land: 800, popCap: 40 } },

    /* ---- 時代4：系 ---- */
    { id: 'newplant', name: '新工場', group: '敷地', desc: '別の土地に工場を建てる。敷地・人・電気がまとめて増える。', unlock: { era: 4 },
      cost: { money: 8e7 }, ratio: 1.6, space: 0, effects: { land: 400, popCap: 40, power: 200, cap: { fecl3: 20000, uw: 20000 } } },
    { id: 'autowh', name: '自動倉庫', group: '保管', desc: '機械が棚を出し入れする。荷役が大きく増え、人が要らなくなる。', unlock: { tech: 'automation' },
      cost: { money: 3e7 }, ratio: 1.4, space: 6, effects: { autohandle: 300, cap: { p_fecl2: 2000, p_hcl: 2000, p_fecl3: 2000, p_fecl3h: 2000, p_naclo: 2000, p_uw: 3000, can: 3000, dcan: 3000 } }, proc: { power: 20 } },
    { id: 'h2rec', name: '水素回収装置', group: '用役', desc: '溶解で出る水素を捨てずに集める。', unlock: { tech: 'loop' },
      cost: { money: 2e7 }, ratio: 1.35, space: 3, effects: { h2rec: 2, cap: { h2: 500 }, circ: { h2: 1 } }, proc: { power: 5 } },
    { id: 'h2tank', name: '水素タンク', group: '保管', desc: '水素をためる。', unlock: { tech: 'loop' },
      cost: { money: 1e7 }, ratio: 1.3, space: 2, effects: { cap: { h2: 3000 } } },
    { id: 'msscrub', name: '多段スクラバー', group: '用役', desc: '排気の酸をほぼすべて回収する。', unlock: { tech: 'loop' },
      cost: { money: 1.5e7 }, ratio: 1.35, space: 3, effects: { vent: 80, hclRecover: 0.15, circ: { hcl: 3 } }, proc: { power: 8 } },
    { id: 'wreuse', name: '排水再生装置', group: '用役', desc: '処理した排水を純水装置の原水に戻す。', unlock: { tech: 'loop' },
      cost: { money: 2.5e7 }, ratio: 1.35, space: 4, effects: { circ: { water: 1 } }, proc: { in: { waste: 30 }, out: { pw: 20 }, power: 6, toggle: true } },
    { id: 'curefine', name: '銅の電解精製', group: '製造', desc: '回収銅を電気で磨き、精製銅にする。めっきの工場へ。', unlock: { tech: 'loop' },
      cost: { money: 3e7 }, ratio: 1.35, space: 4, effects: { cap: { cup: 2000 }, circ: { cu: 2 } }, proc: { in: { cu: 0.5 }, out: { cup: 0.45 }, power: 10, toggle: true } },
    { id: 'farm', name: '汚泥の農地還元', group: '用役', desc: 'ポリシリカ鉄で処理した汚泥を、田畑の土に。', unlock: { tech: 'loop' },
      cost: { money: 1.2e7 }, ratio: 1.4, space: 0, effects: { circ: { sludge: 1 } } },
    { id: 'ureasyn', name: '尿素合成塔', group: '製造', desc: 'アンモニアと二酸化炭素から尿素をつくる。', unlock: { tech: 'ureasyn' },
      cost: { money: 6e7 }, ratio: 1.35, space: 8, effects: { cap: { urea: 20000 } }, proc: { in: { money: 20 }, out: { urea: 40 }, power: 30, toggle: true } },
    { id: 'hpline', name: '高純度薬品ライン', group: '製造', desc: '超純水と精製で、半導体向けの高純度薬品をつくる。', unlock: { tech: 'highpurity' },
      cost: { money: 1.5e8 }, ratio: 1.35, space: 6, effects: { cap: { hp: 5000 } }, proc: { in: { hcl: 5, upw: 4 }, out: { hp: 4 }, power: 20, toggle: true } },
    { id: 'upwplant2', name: '大型超純水システム', group: '用役', desc: '超純水を大量に。', unlock: { tech: 'highpurity' },
      cost: { money: 8e7 }, ratio: 1.35, space: 4, effects: { cap: { upw: 5000 } }, proc: { in: { pw: 15, money: 5 }, out: { upw: 10 }, power: 15, toggle: true } },
    { id: 'pwplant2', name: '大型純水装置', group: '用役', desc: '純水を大量に。', unlock: { tech: 'automation' },
      cost: { money: 2e7 }, ratio: 1.35, space: 4, effects: { cap: { pw: 20000 } }, proc: { in: { money: 8 }, out: { pw: 100 }, power: 20, toggle: true, needs: 'i_cond' } },
    { id: 'megareactor', name: '連続反応塔', group: '製造', desc: '溶解と塩素化を一つの塔で。', unlock: { tech: 'automation' },
      cost: { money: 5e7 }, ratio: 1.25, space: 10, effects: { cap: { fecl3: 10000, fecl3w: 10000 } },
      proc: { in: { scrap: 20, hcl: 40, money: 10 }, out: { fecl3w: 50 }, power: 30, toggle: true, rinse: true, fumes: true } },
    { id: 'port', name: '港の出荷基地', group: '物流', desc: '船で海の向こうへ。', unlock: { tech: 'export' },
      cost: { money: 4e8 }, ratio: 1.6, space: 0, max: 1, effects: { cap: { fecl3: 50000, uw: 50000, hp: 20000 } } },
    { id: 'rnd2', name: '研究都市', group: '研究', desc: '大学と企業が集まる研究の街。', unlock: { era: 4 },
      cost: { money: 2e8 }, ratio: 1.32, space: 0, proc: { in: { money: 1500 }, out: { research: 1500 }, power: 50, toggle: true } },
    { id: 'mega4', name: '閉じた系', group: '大型', desc: '水素・酸・銅・水・缶・汚泥。捨てるものをなくす。循環率90%以上で建設できる。8段階。', unlock: { tech: 'closedloop' },
      cost: { money: 2e9 }, ratio: 1.5, space: 0, stages: 8, buildCond: { circ: 0.9 }, onComplete: { era: 5 } },

    /* ---- 時代5：空 ---- */
    { id: 'electrolysis', name: '水電解装置', group: '宇宙', desc: '純水を電気で分けて、水素をつくる。', unlock: { tech: 'propellant' },
      cost: { money: 2e10 }, ratio: 1.3, space: 0, effects: { cap: { h2: 5000 } }, proc: { in: { pw: 20 }, out: { h2: 2 }, power: 40, toggle: true } },
    { id: 'fusionpower', name: '核融合発電所', group: '宇宙', desc: '重水素の火で、電気を。', unlock: { tech: 'moon' },
      cost: { money: 1e11 }, ratio: 1.35, space: 0, effects: { power: 3000 } },
    { id: 'fuelplant', name: '液化水素プラント', group: '宇宙', desc: '集めた水素を冷やして液体に。ロケット燃料になる。', unlock: { era: 5 },
      cost: { money: 5e9 }, ratio: 1.3, space: 0, effects: { cap: { fuel: 200 } }, proc: { in: { h2: 2 }, out: { fuel: 0.5 }, power: 50, toggle: true } },
    { id: 'launch', name: '打ち上げ場', group: '宇宙', desc: '燃料を燃やして、資材を軌道へ上げる。', unlock: { era: 5 },
      cost: { money: 1e10 }, ratio: 1.35, space: 0, effects: { cap: { orbit: 500 } }, proc: { in: { fuel: 0.5, money: 2e5 }, out: { orbit: 0.2 }, toggle: true } },
    { id: 'moonplant', name: '月面溶解プラント', group: '宇宙', desc: '月の砂には鉄が混じっている。地球の塩酸で溶かす。', unlock: { tech: 'moon' },
      cost: { orbit: 60, money: 5e9 }, ratio: 1.3, space: 0, effects: { cap: { moonfe: 2000 } }, proc: { in: { orbit: 0.01, money: 1e5 }, out: { moonfe: 2 }, toggle: true } },
    { id: 'venus', name: '金星浮遊プラント', group: '宇宙', desc: '金星の雲は硫酸と塩化水素でできている。浮かんで、集める。', unlock: { tech: 'venus' },
      cost: { orbit: 150, money: 2e10 }, ratio: 1.3, space: 0, effects: { cap: { vhcl: 3000 } }, proc: { out: { vhcl: 5 }, in: {}, toggle: true } },
    { id: 'asteroid', name: '小惑星溶解船', group: '宇宙', desc: '鉄とニッケルの塊を、まるごと酸に沈める。', unlock: { tech: 'asteroid' },
      cost: { orbit: 500, money: 5e11 }, ratio: 1.3, space: 0, effects: { cap: { aster: 10000 } }, proc: { in: { vhcl: 1 }, out: { aster: 5 }, toggle: true } },
    { id: 'orbreactor', name: '軌道上反応槽', group: '宇宙', desc: '無重力の反応槽。月の鉄と金星の塩化水素から、宇宙製の塩化第二鉄を。', unlock: { tech: 'venus' },
      cost: { orbit: 200, money: 3e10 }, ratio: 1.3, space: 0, effects: { cap: { sfecl3: 5000 } }, proc: { in: { moonfe: 1, vhcl: 1.5 }, out: { sfecl3: 4 }, toggle: true } },
    { id: 'asteroidreactor', name: '小惑星反応炉', group: '宇宙', desc: '小惑星の鉄を、宇宙製の塩化第二鉄に。', unlock: { tech: 'asteroid' },
      cost: { orbit: 1500, money: 2e12 }, ratio: 1.3, space: 0, proc: { in: { aster: 4, vhcl: 2 }, out: { sfecl3: 8 }, toggle: true } },
    { id: 'spacewater', name: '宇宙の水処理', group: '宇宙', desc: '月面基地と軌道ステーションの水を、宇宙製の凝集剤で澄ませる。', unlock: { tech: 'moon' },
      cost: { orbit: 100, money: 1e10 }, ratio: 1.25, space: 0, effects: { gmul: 1.1 }, proc: { in: { sfecl3: 0.5 }, out: { money: 4e8 }, toggle: true } },
    { id: 'orbtank', name: '軌道上タンク', group: '宇宙', desc: '宇宙で液をためる。', unlock: { tech: 'moon' },
      cost: { orbit: 80, money: 3e10 }, ratio: 1.3, space: 0, effects: { cap: { orbit: 1000, moonfe: 3000, sfecl3: 5000, vhcl: 3000, fuel: 300 } } },
    { id: 'spacelab', name: '軌道研究所', group: '宇宙', desc: '無重力で、地上ではできない実験を。', unlock: { era: 5 },
      cost: { orbit: 50, money: 2e10 }, ratio: 1.3, space: 0, proc: { in: { money: 1e5 }, out: { research: 1e5 }, toggle: true } },
    { id: 'mega5', name: '軌道エレベーター', group: '大型', desc: '地球と宇宙を一本の綱でつなぐ。10段階。', unlock: { tech: 'elevator' },
      cost: { orbit: 400, money: 2e13 }, ratio: 1.5, space: 0, stages: 10, onComplete: { era: 6 } },

    /* ---- 時代6：星 ---- */
    { id: 'starfurnace', name: '恒星炉', group: '星', desc: '鉄は、星が最後につくる元素。星の芯を炉にする。', unlock: { era: 6 },
      cost: { orbit: 5000, money: 5e13 }, ratio: 1.7, space: 0, effects: { gmul: 3, cap: { star: 1e6, gfe: 1e6 } }, proc: { out: { star: 10, gfe: 3 }, in: {}, toggle: true } },
    { id: 'ismnet', name: '星間雲回収網', group: '星', desc: '星間雲には塩化水素も尿素も漂っている。網で集める。', unlock: { tech: 'ism' },
      cost: { star: 5000, money: 1e17 }, ratio: 1.7, space: 0, effects: { gmul: 3, cap: { ism: 1e6 } }, proc: { in: { star: 0.5 }, out: { ism: 5 }, toggle: true } },
    { id: 'galwater', name: '銀河水処理網', group: '星', desc: '銀河じゅうの水を澄ませる。', unlock: { tech: 'galaxy' },
      cost: { gfe: 2e4, ism: 2e4, money: 1e20 }, ratio: 1.8, space: 0, effects: { gmul: 5 }, proc: { in: { gfe: 0.2, ism: 0.2 }, out: { money: 1e15 }, toggle: true } },
    { id: 'starlorry', name: '恒星間ローリー', group: '星', desc: '光の速さの手前で、液を運ぶ。', unlock: { tech: 'galaxy' },
      cost: { star: 1e5, money: 1e22 }, ratio: 1.8, space: 0, effects: { gmul: 5 } },
    { id: 'alien', name: '異星の商会', group: '星', desc: 'ケイ素の体をもつ取引先。星間物質を高く買ってくれる。', unlock: { tech: 'ism' },
      cost: { ism: 1e4, money: 1e18 }, ratio: 1.7, space: 0, effects: { gmul: 3 }, proc: { in: { ism: 0.3 }, out: { money: 1e13 }, toggle: true } },
    { id: 'starlab', name: '恒星計算機', group: '星', desc: '星ひとつぶんの計算機。', unlock: { era: 6 },
      cost: { star: 2000, money: 1e16 }, ratio: 1.4, space: 0, proc: { in: { star: 0.1 }, out: { research: 1e8 }, toggle: true } },
    { id: 'starstore', name: '星間倉庫', group: '星', desc: '星の鉄と星間物質をためる。', unlock: { era: 6 },
      cost: { money: 5e16 }, ratio: 1.6, space: 0, effects: { cap: { star: 1e7, gfe: 1e7, ism: 1e7 } } },
    { id: 'final', name: '始まりの釜', group: '大型', desc: '宇宙そのものを、一つの釜に。10段階。', unlock: { tech: 'origin' },
      cost: { money: 3e33, star: 1e6, ism: 1e6, gfe: 1e6 }, ratio: 1e3, ratioRes: { star: 2.5, ism: 2.5, gfe: 2.5 }, space: 0, stages: 10, onComplete: { ending: true } }
  ],

  /* フック：まだ買えない先の設備・技術の名前だけを見せる */
  teasers: ['ベルトコンベア', '自動洗缶ライン', 'フォークリフト', '天井クレーン', 'タンクローリー', '分析室', '純水装置', 'ICP発光分光分析装置', '脱銅処理設備'],
  teaserTechs: ['濃縮', '脱銅', '超純水', '尿素水', '推進剤', '大気化学', '恒星元素合成'],

  /* ---------------- 技術 ---------------- */
  techs: [
    { id: 'suppliers', name: '仕入れ先', desc: '鉄くずや塩酸を届けてくれる相手を探す。', cost: { research: 25 }, era: 1 },
    { id: 'ventilation', name: '換気', desc: '泡は水素。酸の霧は目にしみる。風を通そう。', cost: { research: 15 }, era: 1, setFlag: 'smoke' },
    { id: 'delivery', name: '配達', desc: '荷台のある車があれば、町まで届けられる。', cost: { research: 40 }, era: 1, req: ['suppliers'] },
    { id: 'electric', name: '電気', desc: '機械を動かすには電気が要る。', cost: { research: 30 }, era: 1, setFlag: 'power_known' },
    { id: 'poison', name: '劇物の取り扱い', desc: '濃い塩酸は劇物。扱う人には資格が要る。', cost: { research: 60 }, era: 1, req: ['suppliers'] },
    { id: 'bookkeeping', name: '帳簿', desc: '月ごとの損益をつける。', cost: { research: 50 }, era: 1 },
    { id: 'reactor', name: '反応槽', desc: 'FRPの大きな槽なら、酸に負けない。', cost: { research: 120 }, era: 1, req: ['electric'] },
    { id: 'chlorination', name: '塩素化', desc: '第一鉄に塩素を通すと、第二鉄になる。液は赤褐色に変わる。', cost: { research: 220 }, era: 1, req: ['reactor'] },
    { id: 'scrubbing', name: '排ガス処理', desc: '排気を水で洗えば、酸が回収できる。', cost: { research: 200 }, era: 1, req: ['ventilation', 'reactor'] },
    { id: 'factory', name: '工場', desc: '屋根と壁と、まとまった敷地。', cost: { research: 400 }, era: 1, req: ['chlorination', 'bookkeeping'] },

    { id: 'analysis', name: '分析', desc: '目で見るより、測ったほうが確かだ。', cost: { research: 675 }, era: 2 },
    { id: 'logistics', name: '荷役', desc: 'パレットに積めば、まとめて動かせる。', cost: { research: 525 }, era: 2 },
    { id: 'racking', name: '高積み', desc: '上へ積めば、床が空く。', cost: { research: 1200 }, era: 2, req: ['logistics'] },
    { id: 'trucks', name: 'トラック', desc: '県内まで届けられる。', cost: { research: 900 }, era: 2 },
    { id: 'trucks2', name: '大きなトラック', desc: '一度にたくさん運ぶ。', cost: { research: 2625 }, era: 2, req: ['trucks'] },
    { id: 'washing', name: '洗缶の機械化', desc: '缶を洗う機械。', cost: { research: 1050 }, era: 2 },
    { id: 'wastewater', name: '排水処理', desc: '自分たちの液で、自分たちの水を澄ませる。', cost: { research: 1350 }, era: 2, req: ['washing'] },
    { id: 'filling', name: '充填の機械化', desc: '決まった量を、機械に注がせる。', cost: { research: 1500 }, era: 2 },
    { id: 'conveyor', name: 'ベルトコンベア', desc: '缶を流せば、人は動かなくていい。', cost: { research: 3375 }, era: 2, req: ['filling'] },
    { id: 'substation', name: '高圧受電', desc: '機械が増えれば、電気も要る。', cost: { research: 3000 }, era: 2 },
    { id: 'concentration', name: '濃縮', desc: '煮詰めれば、濃く、高く売れる。', cost: { research: 3750 }, era: 2, req: ['analysis'] },
    { id: 'bigpack', name: 'ドラムとコンテナ', desc: '大口の客は、大きな入れ物で欲しがる。', cost: { research: 4500 }, era: 2, req: ['logistics'], effects: [['demand', 0.3]] },
    { id: 'crane', name: '天井クレーン', desc: '重いものは、上から吊る。', cost: { research: 6000 }, era: 2, req: ['bigpack'] },
    { id: 'plant', name: '連続運転', desc: '止めずに作り続ける工場。', cost: { research: 11250 }, era: 2, req: ['conveyor', 'concentration', 'wastewater', 'racking'] },

    { id: 'lorry', name: 'タンクローリー', desc: '「ローリーで毎週」。液を液のまま運ぶ。', cost: { research: 22500 }, era: 3 },
    { id: 'decopper', name: '脱銅と再生', desc: '「使用済み液を引き取ってくれないか」。銅を取り出し、液は再び第二鉄液へ。', cost: { research: 37500 }, era: 3, req: ['lorry'], setFlag: 'spent_on' },
    { id: 'instruments', name: '精密分析', desc: '紫外可視、原子吸光。見えないものを数える。', cost: { research: 45000 }, era: 3 },
    { id: 'hypo', name: '次亜塩素酸ソーダ', desc: '浄水場「次亜もまとめてお願いできますか」。', cost: { research: 60000 }, era: 3, req: ['instruments'] },
    { id: 'coagulants', name: '凝集剤の品揃え', desc: 'PAC、ポリ硫酸第二鉄、ポリシリカ鉄。水を澄ませる方法はいくつもある。', cost: { research: 75000 }, era: 3, req: ['instruments'] },
    { id: 'purewater', name: '純水', desc: '水道水から、不純物を一つずつ取り除く。', cost: { research: 67500 }, era: 3 },
    { id: 'urea', name: '尿素水', desc: '運送会社「ディーゼル車の排ガスをきれいにする液を」。尿素32.5%。', cost: { research: 150000 }, era: 3, req: ['purewater', 'instruments'] },
    { id: 'autowash', name: '自動洗缶', desc: '缶を洗う工程を、すべて機械に。', cost: { research: 112500 }, era: 3 },
    { id: 'oem', name: '受託製造', desc: '「困っていること、ありませんか」。他社の製造を引き受ける。', cost: { research: 90000 }, era: 3 },
    { id: 'dispatch', name: '配車システム', desc: '配送・空缶回収・原料引取を、一つの表で回す。', cost: { research: 187500 }, era: 3, effects: [['transport', 0.5], ['return', 0.2]] },
    { id: 'depot', name: '全国配送', desc: '中継デポを置けば、全国に届く。', cost: { research: 375000 }, era: 3, req: ['lorry', 'dispatch'] },
    { id: 'terminal', name: '貯蔵出荷基地', desc: '大きなタンクを並べ、他社の液も預かる。', cost: { research: 600000 }, era: 3, req: ['urea', 'decopper', 'hypo', 'coagulants', 'oem'] },

    { id: 'automation', name: '自動化', desc: '計装・自動小分け装置・ロボット。人は考えることに回る。', cost: { research: 3e+06 }, era: 4, effects: [['auto.operate', 1], ['job.research', 1]] },
    { id: 'autoline', name: '無人ライン', desc: '小分けラインを人なしで。', cost: { research: 6e+06 }, era: 4, req: ['automation'], effects: [['auto.line', 1], ['line.fill', 1], ['line.pallet', 1], ['line.feed', 1], ['linespeed', 1]] },
    { id: 'autofork', name: '無人搬送', desc: 'フォークリフトも、自分で走る。', cost: { research: 6e+06 }, era: 4, req: ['automation'], effects: [['auto.fork', 1]] },
    { id: 'loop', name: '循環', desc: '捨てていたものを、一つずつ拾い直す。', cost: { research: 4.5e+06 }, era: 4 },
    { id: 'ureasyn', name: '尿素の合成', desc: 'アンモニアと二酸化炭素から。', cost: { research: 9e+06 }, era: 4, req: ['loop'] },
    { id: 'highpurity', name: '高純度', desc: '半導体の工場は、ppbの不純物も嫌う。', cost: { research: 1.5e+07 }, era: 4, req: ['automation'] },
    { id: 'foodgrade', name: '食品添加物', desc: '添加物製造の許可。浄水場と食品工場のために。', cost: { research: 1.12e+07 }, era: 4, effects: [['contract', 0.5]] },
    { id: 'export', name: '海の向こう', desc: '船に積めば、海外の客にも届く。', cost: { research: 3e+07 }, era: 4, req: ['highpurity'], effects: [['zone', 1]] },
    { id: 'closedloop', name: '閉じた系', desc: 'すべてを回収すれば、工場は一つの生き物になる。', cost: { research: 6e+07 }, era: 4, req: ['loop', 'ureasyn', 'export'] },

    { id: 'propellant', name: '推進剤', desc: '捨てていた泡が、空へ昇る燃料になる。', cost: { research: 5e8 }, era: 5, effects: [['bld.fuelplant', 1]] },
    { id: 'moon', name: '月面冶金', desc: '月の砂には、鉄が混じっている。', cost: { research: 1e9 }, era: 5, req: ['propellant'] },
    { id: 'venus', name: '大気化学', desc: '金星の雲は硫酸と塩化水素でできている。仕入れ先が一つ増えた。', cost: { research: 3e9 }, era: 5, req: ['moon'] },
    { id: 'asteroid', name: '小惑星', desc: '鉄とニッケルの塊が、太陽のまわりを回っている。', cost: { research: 1e10 }, era: 5, req: ['venus'] },
    { id: 'elevator', name: '軌道エレベーター', desc: '打ち上げずに、昇る。', cost: { research: 5e10 }, era: 5, req: ['asteroid'] },

    { id: 'nucleo', name: '恒星元素合成', desc: '鉄は、星が最後につくるもの。ずっと、星の灰を溶かしていた。', cost: { research: 5e12 }, era: 6, effects: [['global', 1]] },
    { id: 'ism', name: '星間化学', desc: '星と星のあいだにも、塩化水素と尿素がある。', cost: { research: 3e13 }, era: 6, req: ['nucleo'] },
    { id: 'galaxy', name: '銀河規模の物流', desc: '一番遠い客にも、ローリーは行く。', cost: { research: 1e16 }, era: 6, req: ['ism'] },
    { id: 'origin', name: '宇宙反応工学', desc: '宇宙そのものが、巨大な反応槽だった。', cost: { research: 5e18 }, era: 6, req: ['galaxy'] }
  ],

  /* ---------------- 改善（一度だけ買える強化） ---------------- */
  upgrades: [
    { id: 'gloves', name: '厚手の手袋', desc: '溶解 +50%。手で溶かす量も増える。', cost: { money: 40 }, unlock: { era: 1, job: { dissolve: 1 } }, effects: [['job.dissolve', 0.5], ['manual.dissolve', 0.5]] },
    { id: 'bucket', name: '鉄のバケツ', desc: '回収 +50%', cost: { money: 70 }, unlock: { era: 1, any: [{ upg: 'gloves' }, { flag: 'raw_full' }] }, effects: [['job.gather', 0.5]] },
    { id: 'funnel', name: 'じょうご', desc: '充填 +30%', cost: { money: 80 }, unlock: { flag: 'cans_known' }, effects: [['job.fill', 0.3]] },
    { id: 'cart', name: '台車', desc: '歩いての配達 ×2', cost: { money: 200 }, unlock: { flag: 'cans_known' }, effects: [['walk', 1.0]] },
    { id: 'brush', name: 'ブラシ', desc: '洗缶 +50%', cost: { money: 120 }, unlock: { flag: 'dcan_known' }, effects: [['job.wash', 0.5]] },
    { id: 'shopsign', name: '店先の札', desc: '店先の客が倍になり、店番も手際よくなる。', cost: { money: 150 }, unlock: { era: 1, flag: 'walkin_empty' }, effects: [['shop', 1]] },
    { id: 'abacus', name: 'そろばん', desc: '研究 +50%', cost: { money: 300 }, unlock: { flag: 'research_known' }, effects: [['job.research', 0.5]] },
    { id: 'handpump', name: 'ハンドポンプ', desc: '充填 +60%', cost: { money: 450 }, unlock: { flag: 'cans_known', res: { money: 200 } }, effects: [['job.fill', 0.6]] },
    { id: 'scale', name: '台はかり', desc: '充填 +40%、量が正確になり信用が上がりやすくなる', cost: { money: 350 }, unlock: { flag: 'cans_known', res: { money: 200 } }, effects: [['job.fill', 0.4], ['credit', 0.2]] },
    { id: 'bigkama', name: '大釜', desc: '溶解 +50%', cost: { money: 900 }, unlock: { bld: { kama: 3 } }, effects: [['job.dissolve', 0.5]] },
    { id: 'returnbox', name: '回収箱', desc: '空き缶が戻ってくる割合 +15%', cost: { money: 600 }, unlock: { flag: 'dcan_known' }, effects: [['return', 0.15]] },
    { id: 'uniform', name: '作業着', desc: 'すべての配属 +10%', cost: { money: 800 }, unlock: { pop: 6 }, effects: [['job.all', 0.1]] },
    { id: 'signboard', name: '看板', desc: '注文 +30%', cost: { money: 1200 }, unlock: { flag: 'cans_known', res: { money: 600 } }, effects: [['demand', 0.3]] },
    { id: 'stirrer', name: '撹拌機', desc: '溶解 +50%、反応槽 +25%', cost: { money: 2000 }, unlock: { flag: 'power_known' }, effects: [['job.dissolve', 0.5], ['bld.reactor', 0.25]] },
    { id: 'hydrometer', name: '比重計', desc: '検査 +100%、第二鉄液の品質 +10%', cost: { money: 1500 }, unlock: { tech: 'chlorination' }, effects: [['job.check', 1.0], ['quality', 0.1]] },
    { id: 'bigtank', name: '大きな液だめ', desc: '第一鉄液・第二鉄液を置ける量 +50%', cost: { money: 2500 }, unlock: { tech: 'reactor' }, effects: [['cap.fecl2', 0.5], ['cap.fecl3', 0.5], ['cap.fecl3w', 0.5]] },
    { id: 'notebook', name: '作業日誌', desc: '研究 +50%', cost: { money: 3000 }, unlock: { tech: 'bookkeeping' }, effects: [['job.research', 0.5]] },
    { id: 'routeplan', name: '配達順の工夫', desc: '配達・運搬 +25%', cost: { money: 4000 }, unlock: { tech: 'delivery' }, effects: [['transport', 0.25]] },

    { id: 'handlift', name: 'ハンドリフト', desc: '荷役 ×2', cost: { money: 3000 }, unlock: { tech: 'logistics' }, effects: [['job.handle', 1.0]] },
    { id: 'hpwasher', name: '高圧洗浄機', desc: '洗缶 ×2', cost: { money: 3500 }, unlock: { tech: 'washing' }, effects: [['job.wash', 1.0]] },
    { id: 'safety', name: '保護具の更新', desc: 'すべての配属 +10%', cost: { money: 6000 }, unlock: { era: 2 }, effects: [['job.all', 0.1]] },
    { id: 'bulkacid', name: '塩酸の大口契約', desc: '塩酸の配達 +50%（同じ代金で）', cost: { money: 12000 }, unlock: { era: 2 }, effects: [['bld.acidbuy.out', 0.5]] },
    { id: 'library', name: '技術書の棚', desc: '技術をためておける量 ×3', cost: { money: 15000 }, unlock: { era: 2 }, effects: [['cap.research', 2]] },
    { id: 'lotlabel', name: 'ロット番号の印字', desc: 'クレーム時の信用の減りを半分に', cost: { money: 6000 }, unlock: { tech: 'conveyor' }, effects: [['claimHalf', 1]] },
    { id: 'm_capper', name: 'キャッパー', desc: 'ライン：キャップ締めを機械に', cost: { money: 9000 }, unlock: { bld: { line: 1 } }, effects: [['line.cap', 1]] },
    { id: 'm_labeler', name: 'ラベラー', desc: 'ライン：ラベル貼りを機械に', cost: { money: 12000 }, unlock: { bld: { line: 1 } }, effects: [['line.label', 1]] },
    { id: 'm_weigher', name: '重量チェッカー', desc: 'ライン：全数を量る。内容量不足のクレームがなくなる', cost: { money: 15000 }, unlock: { bld: { line: 1 } }, effects: [['line.weigh', 1]] },
    { id: 'm_nozzle', name: '多ノズル充填機', desc: 'ライン：一度に4缶注ぐ', cost: { money: 26000 }, unlock: { upg: 'm_capper' }, effects: [['line.fill', 1]] },
    { id: 'm_palletizer', name: '半自動パレタイザ', desc: 'ライン：パレット積みを機械に', cost: { money: 30000 }, unlock: { upg: 'm_labeler' }, effects: [['line.pallet', 1]] },
    { id: 'm_feeder', name: '缶の自動供給', desc: 'ライン：缶を並べる手間をなくす', cost: { money: 34000 }, unlock: { upg: 'm_nozzle' }, effects: [['line.feed', 1]] },
    { id: 'steamtrap', name: '蒸気配管の保温', desc: '濃縮 +30%', cost: { money: 30000 }, unlock: { bld: { conc: 1 } }, effects: [['bld.conc', 0.3]] },

    { id: 'u_ro', name: '逆浸透膜の更新', desc: '純水装置 +50%', cost: { money: 600000 }, unlock: { bld: { pwplant: 1 } }, effects: [['bld.pwplant', 0.5]] },
    { id: 'u_ix', name: 'イオン交換樹脂の再生', desc: '純水装置 +50%', cost: { money: 900000 }, unlock: { upg: 'u_ro' }, effects: [['bld.pwplant', 0.5]] },
    { id: 'u_uv', name: '紫外線殺菌の強化', desc: '純水の質が上がり、超純水装置 +50%', cost: { money: 1200000 }, unlock: { upg: 'u_ix' }, effects: [['bld.upwplant', 0.5]] },
    { id: 'lotsize', name: 'ロットの大型化', desc: '大きなバッチで、検査 +50%', cost: { money: 800000 }, unlock: { bld: { bigreactor: 1 } }, effects: [['check', 0.5]] },
    { id: 'cuassay', name: '銅濃度の管理', desc: '原子吸光で銅を測り、脱銅 +50%', cost: { money: 1500000 }, unlock: { bld: { decopper: 1, i_aa: 1 } }, effects: [['bld.decopper', 0.5]] },
    { id: 'winterstock', name: '冬の備え', desc: '尿素水の注文 +40%', cost: { money: 3000000 }, unlock: { bld: { ureadis: 1 } }, effects: [['demand.b_uw', 0.4], ['demand.p_uw', 0.4]] },
    { id: 'virgin', name: 'バージン品とリサイクル品', desc: '原料の違う2つのグレードで、客の好みに応える。第二鉄液の単価 +20%', cost: { money: 2500000 }, unlock: { bld: { decopper: 1 } }, effects: [['price.b_fecl3', 0.2], ['price.p_fecl3', 0.2]] },
    { id: 'lorrywash', name: 'ローリーの洗浄設備', desc: 'ローリー出荷 +30%', cost: { money: 5000000 }, unlock: { bld: { lorry: 2 } }, effects: [['bulk', 0.3]] },
    { id: 'iso', name: '品質の約束', desc: '仕組みで品質を守る。品質 +10%、受託の評価が通りやすくなる', cost: { money: 8000000 }, unlock: { era: 3 }, effects: [['quality', 0.1]] },
    { id: 'eco', name: '環境の約束', desc: '環境への配慮を仕組みに。注文 +20%', cost: { money: 8000000 }, unlock: { era: 3 }, effects: [['demand', 0.2]] },
    { id: 'robot', name: 'ロボットパレタイザ', desc: '小分けライン +50%', cost: { money: 4e7 }, unlock: { tech: 'automation' }, effects: [['linespeed', 0.5]] },
    { id: 'autosub', name: '自動小分け装置', desc: '充填 +100%', cost: { money: 6e7 }, unlock: { tech: 'automation' }, effects: [['filler', 1], ['job.fill', 1]] },
    { id: 'h2burner', name: '水素ボイラー', desc: '集めた水素を燃料に。濃縮・尿素溶解 +30%', cost: { money: 5e7 }, unlock: { bld: { h2rec: 1 } }, effects: [['bld.conc', 0.3], ['bld.ureadis', 0.3]] },
    { id: 'solar', name: '屋根の太陽光', desc: '使える電気 +30%', cost: { money: 3e7 }, unlock: { era: 4 }, effects: [['power', 0.3]] },
    { id: 'semigrade', name: '半導体グレード', desc: '高純度薬品の単価 +50%', cost: { money: 3e8 }, unlock: { bld: { hpline: 1 } }, effects: [['price.b_hp', 0.5]] },
    { id: 'cryo', name: '断熱タンク', desc: 'ロケット燃料・軌道資材の置き場 ×3', cost: { money: 2e10 }, unlock: { era: 5 }, effects: [['cap.fuel', 2], ['cap.orbit', 2]] },
    { id: 'reuse_rocket', name: '再使用ロケット', desc: '打ち上げ場 +100%', cost: { money: 1e11 }, unlock: { bld: { launch: 1 } }, effects: [['bld.launch', 1]] },
    { id: 'zerog', name: '無重力の撹拌', desc: '宇宙の反応 +100%', cost: { money: 2e12 }, unlock: { bld: { orbreactor: 1 } }, effects: [['bld.orbreactor', 1], ['bld.asteroidreactor', 1]] },
    { id: 'stargrade', name: '宇宙規格', desc: '宇宙の水処理 +100%', cost: { money: 5e12 }, unlock: { bld: { spacewater: 3 } }, effects: [['bld.spacewater', 1]] },
    { id: 'dyson', name: '星を包む配管', desc: 'すべての生産 ×2', cost: { money: 1e19, star: 1e5 }, unlock: { bld: { starfurnace: 3 } }, effects: [['global', 1]] },
    { id: 'lightcone', name: '光円錐の配車', desc: 'すべての生産 ×2', cost: { money: 1e24, ism: 1e5 }, unlock: { bld: { starlorry: 1 } }, effects: [['global', 1]] }
  ],

  /* 小分けラインのモジュール（能力：缶/秒） */
  lineModules: [
    { id: 'feed', name: '缶供給', levels: [['ベルトコンベア', 0.9], ['自動缶供給機', 2.2], ['無人搬送', 5]] },
    { id: 'fill', name: '充填', levels: [['半自動充填 ×2', 0.45], ['多ノズル充填機', 1.6], ['自動小分け装置', 5]] },
    { id: 'cap', name: 'キャップ締め', levels: [['手で締める', 0.2], ['キャッパー', 1.8]] },
    { id: 'label', name: 'ラベル', levels: [['印刷ラベルを手で貼る', 0.3], ['ラベラー', 1.9]] },
    { id: 'weigh', name: '重量検査', levels: [['抜き取り検査', 2.5], ['重量チェッカー', 2.5]] },
    { id: 'pallet', name: 'パレット積み', levels: [['手積み', 0.6], ['半自動パレタイザ', 2.0], ['ロボットパレタイザ', 5]] }
  ],

  /* ---------------- 製品と市場 ----------------
     kind: can=缶で出荷 / bulk=ローリーで出荷 / direct=引き取りに来る
     can の price は1缶（kg）あたり、bulk・direct は1kgあたり */
  products: [
    { id: 'p_fecl2', kind: 'can', container: 'can', liquid: 'fecl2', name: '塩化第一鉄液（缶）', price: 130, demand: 0.006 },
    { id: 'p_hcl', kind: 'can', container: 'can', liquid: 'hcl', name: '塩酸（小分け）', price: 110, demand: 0.005, license: 'geki' },
    { id: 'p_fecl3', kind: 'can', container: 'can', liquid: 'fecl3', name: '塩化第二鉄液（缶）', price: 380, demand: 0.006, quality: true, season: [1, 1.3, 1, 0.85], spent: 0.25 },
    { id: 'p_fecl3h', kind: 'can', container: 'can', liquid: 'fecl3h', name: '塩化第二鉄液 高濃度（缶）', price: 700, demand: 0.004, quality: true, season: [1, 1.3, 1, 0.85], spent: 0.25 },
    { id: 'p_naclo', kind: 'can', container: 'can', liquid: 'naclo', name: '次亜塩素酸ソーダ（缶）', price: 260, demand: 0.02, unlock: { bld: { i_ic: 1 } }, season: [1, 1.4, 1, 0.8] },
    { id: 'p_uw', kind: 'can', container: 'bib', containerCost: 40, liquid: 'uw', name: '尿素水（BIB）', price: 520, demand: 0.03, unlock: { bld: { i_icp: 1, i_refract: 1 } }, season: [1, 0.8, 1, 1.7] },
    { id: 'b_fecl3', kind: 'bulk', src: 'fecl3', name: '塩化第二鉄液（ローリー）', price: 14, demand: 0.5, quality: true, season: [1, 1.3, 1, 0.85], spent: 0.25, creditPer: 0.0005 },
    { id: 'b_fecl3h', kind: 'bulk', src: 'fecl3h', name: '高濃度品（ローリー）', price: 26, demand: 0.3, quality: true, season: [1, 1.3, 1, 0.85], spent: 0.25, creditPer: 0.0005 },
    { id: 'b_naclo', kind: 'bulk', src: 'naclo', name: '次亜塩素酸ソーダ（ローリー）', price: 9, demand: 1.0, unlock: { bld: { i_ic: 1 } }, season: [1, 1.4, 1, 0.8], creditPer: 0.0005 },
    { id: 'b_pac', kind: 'bulk', src: 'pac', name: 'PAC（ローリー）', price: 11, demand: 0.8, unlock: { bld: { i_visc: 1 } }, season: [1, 1.3, 1, 0.9], creditPer: 0.0005 },
    { id: 'b_psi', kind: 'bulk', src: 'psi', name: 'ポリシリカ鉄（ローリー）', price: 22, demand: 0.4, unlock: { bld: { i_visc: 1 } }, season: [1.2, 1.3, 1, 0.9], creditPer: 0.0005 },
    { id: 'b_uw', kind: 'bulk', src: 'uw', name: '尿素水（ローリー）', price: 18, demand: 1.5, unlock: { bld: { i_icp: 1, i_refract: 1 } }, season: [1, 0.8, 1, 1.7], creditPer: 0.0005 },
    { id: 'b_hp', kind: 'bulk', src: 'hp', name: '高純度薬品', price: 400, demand: 1.0, quality: true, creditPer: 0.001 },
    { id: 'cu', kind: 'direct', src: 'cu', name: '回収銅', price: 900, demand: 0.05, handling: 0.02 },
    { id: 'cup', kind: 'direct', src: 'cup', name: '精製銅', price: 2500, demand: 0.2, handling: 0.02 }
  ],
  zones: [
    { name: '近所', demand: 1, price: 1 },
    { name: '町', demand: 4, price: 1.1 },
    { name: '県内', demand: 18, price: 1.2 },
    { name: '地方', demand: 60, price: 1.25 },
    { name: '全国', demand: 250, price: 1.3 },
    { name: '海外', demand: 1500, price: 1.5 }
  ],
  seasons: ['春', '夏', '秋', '冬'],
  eraSalary: [0, 0.3, 2.5, 8, 30, 200, 1000],

  /* 循環率（時代4）：need は満点になる設備の能力 */
  circ: [
    { id: 'hcl', name: '酸', weight: 1, need: 6 },
    { id: 'h2', name: '水素', weight: 1, need: 6 },
    { id: 'water', name: '水', weight: 1, need: 5 },
    { id: 'cu', name: '銅', weight: 1, need: 12 },
    { id: 'can', name: '缶', weight: 1, need: 12 },
    { id: 'sludge', name: '汚泥', weight: 1, need: 3 }
  ],
  circBonus: 1.5,

  /* ---------------- 受託製造 ---------------- */
  contracts: {
    tech: 'oem', offerSec: 240, scaleBase: 6,
    steps: [
      { id: 'hearing', name: 'ヒアリング', sec: 60 },
      { id: 'study', name: '製造方法・規格の検討', sec: 180, needs: true },
      { id: 'sample', name: 'サンプル製造', sec: 240 },
      { id: 'eval', name: 'サンプル評価', sec: 300 },
      { id: 'final', name: '最終仕様の決定', sec: 60 },
      { id: 'production', name: '製品化', sec: 600 },
      { id: 'pack', name: '梱包・納入', sec: 120 }
    ],
    templates: [
      { id: 'dilute', name: '工業薬品の希釈・調合・溶解', income: 60, use: { pw: 1 }, needs: { study: { bld: { i_refract: 1, pwplant: 1 } } } },
      { id: 'metal', name: '使用済廃液からのメタル精製', income: 90, use: { spent: 0.5 }, needs: { study: { bld: { decopper: 1, i_aa: 1 } } } },
      { id: 'subpack', name: '工業薬品の小分け梱包', income: 70, use: { can: 0.05 }, needs: { study: { bld: { line: 2 } } } },
      { id: 'canwash', name: 'ポリ缶洗浄', income: 50, use: { pw: 0.3 }, needs: { study: { bld: { canline: 1 } } } },
      { id: 'other', name: 'その他工業薬品の製造', income: 80, use: { hcl: 1 }, needs: { study: { bld: { bigreactor: 2 } } } },
      { id: 'poison', name: '毒劇物の製造', income: 130, use: { hcl: 1.5 }, needs: { study: { lic: { geki: 3 } } } },
      { id: 'food', name: '食品添加物の製造', income: 220, use: { pw: 2 }, unlock: { tech: 'foodgrade' }, needs: { study: { bld: { i_ftir: 1, i_icp: 1 } } } },
      { id: 'smalllot', name: '小ロット製造', income: 55, use: {}, needs: { study: { bld: { filler: 3 } } } },
      { id: 'custom', name: '専用設備の改良や新設', income: 160, use: {}, needs: { study: { bld: { substation: 2 } } } },
      { id: 'storage', name: '貯蔵出荷基地としての保管', income: 120, use: {}, needs: { study: { bld: { shiptank: 3 } } } },
      { id: 'unknown', name: '中身の分からない廃液の判定と処理', income: 140, use: { fecl3: 1 }, needs: { study: { bld: { i_ftir: 1 } } } }
    ]
  },

  /* ---------------- 流れの診断 ----------------
     raw：仕入れる原料、liquid：つくった液。fixes：詰まりの種類ごとの手当て（上から順に、見えているものを3つまで出す） */
  flow: {
    raw: ['scrap', 'hcl', 'urea', 'spent', 'pw', 'upw'],
    liquid: ['fecl2', 'fecl3w', 'fecl3', 'fecl3h', 'nacw', 'naclo', 'pac', 'psi', 'uww', 'uw', 'hp', 'cu', 'cup'],
    fixes: {
      scrap: [['job', 'gather'], ['act', 'pick'], ['bld', 'scrapbuy'], ['bld', 'scrapyard'], ['upg', 'bucket']],
      hcl: [['act', 'buyacid'], ['bld', 'acidbuy'], ['bld', 'acidtank'], ['upg', 'bulkacid']],
      urea: [['bld', 'ureabuy'], ['bld', 'ureasyn']],
      spent: [['bld', 'decopper']],
      pw: [['bld', 'pwplant'], ['upg', 'u_ro'], ['bld', 'pwplant2'], ['bld', 'wreuse']],
      upw: [['bld', 'upwplant'], ['upg', 'u_uv'], ['bld', 'upwplant2']],
      fecl2: [['job', 'dissolve'], ['bld', 'kama'], ['bld', 'reactor'], ['bld', 'bigreactor'], ['job', 'operate']],
      next: [['job', 'operate'], ['bld', 'chlor'], ['bld', 'bigchlor'], ['bld', 'megareactor'], ['bld', 'conc']],
      fecl3: [['job', 'check'], ['bld', 'chlor'], ['bld', 'bigchlor'], ['bld', 'decopper']],
      money: [['act', 'give'], ['job', 'deliver']],
      make: [['job', 'dissolve'], ['act', 'sink'], ['upg', 'gloves'], ['bld', 'kama'], ['upg', 'stirrer'], ['bld', 'reactor'], ['bld', 'bigreactor'], ['bld', 'megareactor']],
      slots: [['bld', 'kama'], ['upg', 'bigkama'], ['bld', 'reactor'], ['bld', 'bigreactor']],
      operator: [['job', 'operate']],
      power: [['bld', 'powerc'], ['bld', 'substation'], ['upg', 'solar'], ['bld', 'fusionpower']],
      handling: [['job', 'handle'], ['upg', 'handlift'], ['bld', 'fork'], ['bld', 'crane'], ['bld', 'autowh']],
      vent: [['bld', 'vent'], ['bld', 'scrubber'], ['bld', 'msscrub']],
      check: [['job', 'check'], ['upg', 'hydrometer'], ['bld', 'lab'], ['bld', 'i_refract'], ['bld', 'lab2'], ['upg', 'lotsize']],
      cans: [['act', 'buycans'], ['bld', 'canbuy'], ['job', 'wash'], ['upg', 'brush'], ['bld', 'canwasher'], ['bld', 'canline']],
      fill: [['job', 'fill'], ['upg', 'funnel'], ['upg', 'handpump'], ['upg', 'scale'], ['bld', 'filler'], ['bld', 'line'], ['upg', 'm_capper'], ['upg', 'autosub']],
      transport: [['job', 'deliver'], ['act', 'give'], ['upg', 'cart'], ['bld', 'kei'], ['upg', 'routeplan'], ['bld', 'truck2'], ['bld', 'truck4']],
      bulk: [['bld', 'lorry'], ['bld', 'lorry20'], ['upg', 'lorrywash'], ['tech', 'dispatch']],
      demand: [['upg', 'signboard'], ['tech', 'delivery'], ['bld', 'kei'], ['tech', 'trucks'], ['bld', 'truck2'], ['bld', 'drum'], ['upg', 'eco'], ['tech', 'depot'], ['tech', 'export']],
      walkin: [['upg', 'shopsign'], ['act', 'give']],
      waste: [['bld', 'neutral'], ['bld', 'coag'], ['tech', 'wastewater'], ['bld', 'wreuse'], ['bld', 'canbuy'], ['act', 'buycans']]
    }
  },

  /* ---------------- 暦 ----------------
     founded：創業年。yearSec：時代ごとの「ゲーム内1年」の秒数（ふつうの遊び方で、だいたい
     時代2≒1960年代、時代3≒1980年代、時代4≒2010年ごろ、時代5≒2040年代、エンディング≒2100年代になる） */
  calendar: {
    founded: 1946,
    yearSec: [7400, 7400, 6700, 6000, 2900, 2000, 1200],
    /* 年商（1年の売上）の節目。一度だけ流れる */
    sales: [
      [1e5, '年商が10万円を超えた。'],
      [1e6, '年商100万円。'],
      [1e7, '年商1000万円。'],
      [1e8, '年商1億円。'],
      [1e9, '年商10億円。'],
      [1e10, '年商100億円。あの泡から、ここまで来た。'],
      [1.2e10, '年商120億円。'],
      [1e11, '年商1000億円。'],
      [1e12, '年商1兆円。'],
      [1e16, '年商1京円。数えるのをやめた人もいる。'],
      [1e20, '年商1垓円。'],
      [1e28, '年商1穣円。'],
      [1e40, '年商1正円。'],
      [1e56, '年商1阿僧祇円。'],
      [1e68, '年商1無量大数円。']
    ],
    anniv: {
      50: '最初の釜のことを、覚えている人はもう少ない。',
      60: '工場の裏に、古い壺がひとつ残っている。',
      70: '缶も、液も、人も、ずいぶん増えた。',
      80: '「ポリ缶に詰めてくれたら、もっと買う」。あの声から、ここまで。',
      100: '百年、溶かし続けてきた。',
      150: '百五十年。社屋の庭の木が大きくなった。',
      200: '二百年。星の地図に、工場の印がついている。'
    },
    annivDefault: ['今日も、どこかで泡が立っている。', '釜の音は、昔と変わらない。', '記念の手ぬぐいを配った。', '社員みんなで、写真を撮った。']
  },

  /* ---------------- 定数 ---------------- */
  consts: {
    tickSec: 0.2,
    canKg: 20,
    walkinPrice: 4,
    walkinRefill: 0.45,
    walkinCap: 15,
    acidBuy: { cost: 10, kg: 6 },
    canBuy: { cost: 75, n: 5 },
    manualDissolveSec: 3,
    manualBatch: { scrap: 1, hcl: 2, fecl2: 3 },
    hireBase: 20, hireRatio: 1.6,
    basePop: 3,
    baseLand: 60,
    basePower: 2,
    baseHandling: 1.2,
    baseVent: 0.35,
    salary: 0.015,
    arrivalSec: 50,
    returnRate: 0.25,
    wasteFree: 0.05,
    /* 与信枠：借りている額にかかる利息(1秒あたり)と、枠を超えてから設備を手放すまでの猶予(秒) */
    creditRate: 0.0001,
    overGrace: 60,
    /* 時代ごとの「そのまま下水に流せる分」(L/秒) と、製造の洗浄水(L/液1kg、時代2から) */
    wasteFreeEra: [0.05, 0.05, 1, 4, 10, 20, 40],
    rinse: 0.02,
    seasonSec: 1200,
    monthSec: 400,
    hookSec: 720,
    memoSec: 900,
    offlineFull: 12 * 3600, offlineHalf: 72 * 3600, offlineHalfRate: 0.25
  },

  /* ---------------- 物語（ログ） ---------------- */
  story: [
    { id: 'eureka_acid', cond: { flag: 'bought_acid' }, text: '店の主人は、それを「塩酸」と呼んだ。', setFlag: 'acid_known' },
    { id: 'bang', cond: { all: [{ flag: 'acid_known' }, { res: { money: 30 } }] }, text: '泡に火を近づけると、ぽんと鳴った。' },
    { id: 'hands', cond: { all: [{ flag: 'sold' }, { stat: { batches: 6 } }] }, text: '一人では手が足りない。', setFlag: 'hire_reveal' },
    { id: 'small', cond: { all: [{ flag: 'hired' }, { stat: { batches: 10 } }] }, text: '壺では小さすぎる。', setFlag: 'kama_reveal' },
    { id: 'named', cond: { era: 1, bld: { kama: 2 } }, text: '測ってみると、緑の液は塩化第一鉄だった。', setFlag: 'fecl2_known' },
    { id: 'nocan', cond: { any: [{ all: [{ upg: 'shopsign' }, { bld: { kama: 2 } }, { res: { fecl2: 12 } }] }, { flag: 'walkin_empty2' }, { all: [{ flag: 'walkin_empty' }, { res: { fecl2: 28 } }, { time: 900 }] }] }, text: '「入れ物に入れてくれたら、もっと買うんだが」', setFlag: 'cans_known' },
    { id: 'dcan', cond: { res: { dcan: 1 } }, text: '空いた缶が残る。捨てるには惜しい缶だ。', setFlag: 'dcan_known' },
    { id: 'smoke', cond: { flag: 'fumes_bad' }, text: 'むせる。目にしみる。風を通さないと。', setFlag: 'smoke' },
    { id: 'power', cond: { flag: 'smoke' }, text: '機械を回すには、電気が要る。', setFlag: 'power_known' },
    { id: 'red', cond: { bld: { chlor: 1 } }, text: '塩素を通すと、液が赤くなった。深い、赤褐色。' },
    { id: 'tight', cond: { flag: 'space_tight' }, text: 'どこにも置けない。土地が足りない。' },
    { id: 'credit', cond: { flag: 'oncredit' }, text: '支払いが追いつかない。銀行が与信枠をつけてくれた。（お金がマイナスでも、枠の中なら設備・仕入れ・給料に使える。利息はつく）' },
    { id: 'era2', cond: { era: 2 }, text: '屋根の下で、釜が鳴る。ここはもう、工場だ。' },
    { id: 'claim', cond: { flag: 'claimed' }, text: '「中身が少ない缶があった」と電話が来た。' },
    { id: 'handling', cond: { flag: 'handling_short' }, text: '缶は積み上がるのに、運ぶ手が足りない。' },
    { id: 'powershort', cond: { all: [{ flag: 'power_short' }, { era: 2 }] }, text: '機械が止まりがちだ。電気が足りない。' },
    { id: 'wastefull', cond: { flag: 'waste_full' }, text: '洗い場の排水があふれそうだ。このままでは流せない。' },
    { id: 'coag', cond: { bld: { coag: 1 } }, text: '汚れた水を、自分たちの液で澄ませた。' },
    { id: 'line', cond: { bld: { line: 1 } }, text: '缶がコンベアの上を流れていく。人は、もう缶を持ち歩かない。' },
    { id: 'era3', cond: { era: 3 }, text: '止まらない工場。「ローリーで毎週、届けてもらえないか」と浄水場から電話が来た。' },
    { id: 'lorry', cond: { stat: { lorryUsed: 1 } }, text: 'ローリーが出ていく。もう台車には戻れない。' },
    { id: 'spent', cond: { tech: 'decopper' }, text: '電子部品の工場から、使い終わった液が戻ってくる。中には銅が溶けている。' },
    { id: 'farmer', cond: { bld: { psiline: 1 } }, text: '「田んぼがよく実った」と、農家から礼状が届いた。' },
    { id: 'urea', cond: { bld: { ureadis: 1 } }, text: '尿素を溶かすと、槽が冷たくなる。湯気で温めながら、32.5%に合わせる。' },
    { id: 'purewater_fight', cond: { all: [{ bld: { i_icp: 1 } }, { bld: { ureadis: 2 } }] }, text: '尿素水が売れるほど、分析室の水が細る。' },
    { id: 'era4', cond: { era: 4 }, text: '捨てていたものが、まだたくさんある。' },
    { id: 'circ', cond: { circ: 0.5 }, text: '水素も、酸も、水も、銅も。少しずつ、輪が閉じていく。' },
    { id: 'era5', cond: { era: 5 }, text: 'あの泡を覚えているか。ぽんと鳴った、あの泡を。いま、それで空へ昇る。' },
    { id: 'venus', cond: { bld: { venus: 1 } }, text: '金星の雲は硫酸と塩化水素でできている。仕入れ先が一つ増えた。' },
    { id: 'era6', cond: { era: 6 }, text: '鉄は、星が最後につくるもの。' },
    { id: 'ash', cond: { tech: 'nucleo' }, text: 'ずっと、星の灰を溶かしていた。' }
  ],

  /* ---------------- 作業メモ ---------------- */
  memos: [
    { text: '釜を2つにする', done: { bld: { kama: 2 } } },
    { text: '人手を4人にする', done: { pop: 4 } },
    { text: 'ポリ缶に詰めて売る', done: { stat: { cansSold: 1 } } },
    { text: '研究で「仕入れ先」を見つける', done: { tech: 'suppliers' } },
    { text: '汚れた缶を洗って使う', done: { stat: { washed: 5 } } },
    { text: '「劇物の取扱責任者」を育てる', done: { lic: { geki: 1 } } },
    { text: '軽トラックで町へ配達する', done: { bld: { kei: 1 } } },
    { text: 'FRP反応槽を据える', done: { bld: { reactor: 1 } } },
    { text: '塩化第二鉄液を作る', done: { stat: { fecl3: 1 } } },
    { text: '帳簿をつける', done: { tech: 'bookkeeping' } },
    { text: '工場の建屋を完成させる', done: { era: 2 } },
    { text: 'フォークリフトを動かす', done: { stat: { forkUsed: 1 } } },
    { text: '2tトラックで県内へ', done: { bld: { truck2: 1 } } },
    { text: '洗缶機を入れる', done: { bld: { canwasher: 1 } } },
    { text: '排水を自分たちの液で処理する', done: { bld: { coag: 1 } } },
    { text: '小分けラインを動かす', done: { bld: { line: 1 } } },
    { text: 'ラインの一番遅い工程を機械にする', done: { upg: 'm_capper' } },
    { text: '高濃度品を作る', done: { stat: { fecl3h: 1 } } },
    { text: '天井クレーンを入れる', done: { bld: { crane: 1 } } },
    { text: '連続プラントを完成させる', done: { era: 3 } },
    { text: 'タンクローリーで出荷する', done: { stat: { lorryUsed: 1 } } },
    { text: '使用済み液から銅を取り出す', done: { bld: { decopper: 1 } } },
    { text: '純水をつくる', done: { bld: { pwplant: 1 } } },
    { text: '尿素水を出荷する', done: { bld: { ureadis: 1, i_icp: 1 } } },
    { text: '受託案件を一つ製品化する', done: { stat: { contractsDone: 1 } } },
    { text: '貯蔵出荷基地を完成させる', done: { era: 4 } },
    { text: '循環率を90%にする', done: { circ: 0.9 } },
    { text: '閉じた系を完成させる', done: { era: 5 } },
    { text: '月で鉄を溶かす', done: { bld: { moonplant: 1 } } },
    { text: '金星の雲から酸を集める', done: { bld: { venus: 1 } } },
    { text: '軌道エレベーターを完成させる', done: { era: 6 } },
    { text: '恒星炉に火を入れる', done: { bld: { starfurnace: 1 } } },
    { text: '始まりの釜を完成させる', done: { stat: { ended: 1 } } }
  ],

  /* ランダムな良い出来事 */
  events: [
    { id: 'goodscrap', text: '質のいい鉄くずが届いた。', button: '受け取る', give: { scrap: 'cap' }, cond: { era: 1 } },
    { id: 'tip', text: '常連さんが、おまけをくれた。', button: 'ありがたく', give: { money: 'income60' }, cond: { flag: 'cans_known' } },
    { id: 'idea', text: '休憩中に、ひらめいた。', button: '書き留める', give: { research: 'cap' }, cond: { flag: 'research_known' } }
  ]
};
